Repository wecode-bootcamp-korea/19-1st-health-vitamin-frontend, pull requests merged in 2021-04, with the labels that each got.

#3 [19기 김효진] ProductList Back 통신, JSON수정, 계산기능 추가
  package-lock.json
  public/data/ProductList/productList.json
  public/index.html
  src/Pages/Basket/Basket.js
  src/Pages/Basket/Basket.scss
  src/Pages/ProductListPage/ProductList.js
  src/Pages/ProductListPage/ProductList.scss
  src/Pages/ProductListPage/ProductListComponent/Products/MovePage/MovePage.jsx
  src/Pages/ProductListPage/ProductListComponent/Products/MovePage/MovePage.scss
  src/Pages/ProductListPage/ProductListComponent/Products/Products.jsx
  src/Pages/ProductListPage/ProductListComponent/Products/Products.scss
  src/Pages/ProductListPage/ProductListComponent/Products/ProductsInfo/ProductsInfo.jsx
  src/Pages/ProductListPage/ProductListComponent/Products/ProductsInfo/ProductsInfo.scss
  src/Pages/ProductListPage/ProductListComponent/Products/ProductsItem/ItemHide.js
  src/Pages/ProductListPage/ProductListComponent/Products/ProductsItem/ProductsItem.jsx
  src/Pages/ProductListPage/ProductListComponent/Products/ProductsItem/ProductsItem.scss
  src/Pages/ProductListPage/ProductListComponent/Title/Title.js
  src/Pages/ProductListPage/ProductListComponent/Title/Title.scss
  src/Routes.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#1 [19기 이종호] Update, Add: ProductInfo페이지 레이아웃 수정 미완(flex대신 margin을 이용해서 정렬이 안됨!!), 이벤트 넣기 완료
  .eslintrc
  .settings.json
  public/data/ProductInfoData/mainImageList.json
  public/data/ProductInfoData/productDetail.json
  public/data/ProductInfoData/subItemList.json
  public/data/ProductInfoData/testDetail.json
  src/Components/CategoryLink/CategoryLink.js
  src/Components/Footer/Footer.js
  src/Components/Nav/Nav.js
  src/Pages/ProductInfoPage/ProductCountBox.js
  src/Pages/ProductInfoPage/ProductCountBox.scss
  src/Pages/ProductInfoPage/ProductDescript.js
  src/Pages/ProductInfoPage/ProductDescript.scss
  src/Pages/ProductInfoPage/ProductDetail.js
  src/Pages/ProductInfoPage/ProductDetail.scss
  src/Pages/ProductInfoPage/ProductInfo.js
  src/Pages/ProductInfoPage/ProductInfo.scss
  src/Pages/ProductInfoPage/ProductInfoHeader.js
  src/Pages/ProductInfoPage/ProductInfoHeader.scss
  src/Pages/ProductInfoPage/ProductInfoimage.js
  src/Pages/ProductInfoPage/ProductInfoimage.scss
  src/Pages/ProductInfoPage/ProductSub.js
  src/Pages/ProductInfoPage/ProductSub.scss
  src/Pages/ProductInfoPage/ProductSubHeader.js
  src/Pages/ProductInfoPage/ProductSubHeader.scss
  src/Pages/ProductInfoPage/ProductSubItem.js
  src/Pages/ProductInfoPage/ProductSubItem.scss
  src/Pages/ProductInfoPage/ProductTotalBox.js
  src/Pages/ProductInfoPage/ProductTotalBox.scss
  src/Routes.js
  src/styles/common.scss
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#2 [19기 강서형] "회원가입 Layout"
  src/Pages/AccountPage/Login.js
  src/Pages/AccountPage/Login.scss
  src/Pages/AccountPage/SignUp.js
  src/Pages/AccountPage/SignUp.scss
  src/Pages/FavoriteProduct/FavoriteProduct.js
  src/Pages/FavoriteProduct/FavoriteProduct.scss
  src/Routes.js
  src/styles/reset.scss
Labels: Status: 수정 요청, Status: 추가 기능 구현중

#7 [19기 이종호] "결제정보 페이지 Layout"
  src/Pages/AccountPage/Login.js
  src/Pages/AccountPage/SignUp.js
  src/Pages/PayPage/Pay.js
  src/Pages/PayPage/Pay.scss
  src/Pages/PayPage/PayBody.js
  src/Pages/PayPage/PayBody.scss
  src/Pages/PayPage/PayBody/PayBenefit.js
  src/Pages/PayPage/PayBody/PayBenefit.scss
  src/Pages/PayPage/PayBody/PayDelivery.js
  src/Pages/PayPage/PayBody/PayDelivery.scss
  src/Pages/PayPage/PayBody/PayDiscount.js
  src/Pages/PayPage/PayBody/PayDiscount.scss
  src/Pages/PayPage/PayBody/PayInfo.js
  src/Pages/PayPage/PayBody/PayInfo.scss
  src/Pages/PayPage/PayBody/PayOrder.js
  src/Pages/PayPage/PayBody/PayOrder.scss
  src/Pages/PayPage/PayBody/PayWay.js
  src/Pages/PayPage/PayBody/PayWay.scss
  src/Pages/PayPage/PayContainer.js
  src/Pages/PayPage/PayContainer.scss
  src/Pages/PayPage/PayHeader.js
  src/Pages/PayPage/PayHeader.scss
  src/Pages/PayPage/PayWay/Cache.js
  src/Pages/PayPage/PayWay/Cache.scss
  src/Pages/PayPage/PayWay/Entrepreneur.js
  src/Pages/PayPage/PayWay/Entrepreneur.scss
  src/Pages/PayPage/PayWay/Individual.js
  src/Pages/PayPage/PayWay/Individual.scss
  src/Pages/PayPage/PayWay/Kakao.js
  src/Pages/PayPage/PayWay/Kakao.scss
  src/Pages/PayPage/PayWay/PGPolicy.js
  src/Pages/PayPage/PayWay/PGPolicy.scss
  src/Pages/PayPage/PayWay/PayWayContent.js
  src/Pages/PayPage/PayWay/RealTimeAccount.js
  src/Pages/PayPage/PayWay/RealTimeAccount.scss
  src/Pages/PayPage/PayWay/SelectWay.js
  src/Pages/PayPage/PayWay/SelectWay.scss
  src/Pages/PayPage/PayWay/SignReceipt.js
  src/Pages/PayPage/PayWay/SignReceipt.scss
  src/Pages/PayPage/PayWay/UseNext.js
  src/Pages/PayPage/PayWay/UseNext.scss
  src/Pages/PayPage/PayWay/VirtualAccount.js
  src/Pages/PayPage/PayWay/VirtualAccount.scss
  src/Pages/PayPage/RadioButton.js
  src/Pages/PayPage/RadioButton.scss
  src/Pages/ProductInfoPage/ProductCountBox.js
  src/Pages/ProductInfoPage/ProductDetail.js
  src/Pages/ProductInfoPage/ProductDetail.scss
  src/Pages/ProductInfoPage/ProductInfoHeader.js
  src/Pages/ProductInfoPage/ProductSubItem.scss
  src/Pages/ProductListPage/ProductList.scss
  src/Pages/ProductListPage/ProductListComponent/Products/ProductsItem/ProductsItem.jsx
  src/Pages/ProductListPage/ProductListComponent/Title/Title.js
  src/Routes.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#5 [19기 강서형] "ADD:관심상품 layout"
  public/data/Favorite/Favorite.json
  src/Pages/AccountPage/Login.js
  src/Pages/AccountPage/SignUp.js
  src/Pages/FavoriteProduct/FavoriteProduct.js
  src/Pages/FavoriteProduct/FavoriteProduct.scss
  src/Routes.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#8 [19기 이종호] "Main페이지 Layout 완료, Pay것도 합쳤습니다.!"
  src/Pages/MainPage/Main.js
  src/Pages/MainPage/Main.scss
  src/Pages/MainPage/MainBody/Banner.js
  src/Pages/MainPage/MainBody/Banner.scss
  src/Pages/MainPage/MainBody/Best.js
  src/Pages/MainPage/MainBody/Best.scss
  src/Pages/MainPage/MainBody/HotKeyword.js
  src/Pages/MainPage/MainBody/HotKeyword.scss
  src/Pages/MainPage/MainBody/JustInfo.js
  src/Pages/MainPage/MainBody/JustInfo.scss
  src/Pages/MainPage/MainBody/RealReview.js
  src/Pages/MainPage/MainBody/RealReview.scss
  src/Pages/PayPage/PayHeader.js
  src/Pages/PayPage/PayHeader.scss
  src/Routes.js
  src/styles/common.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#9 [19기 강서형]Feature/nav Layout 및 기능구현
  src/Pages/AccountPage/Login.js
  src/Pages/FavoriteProduct/FavoriteProduct.js
  src/Pages/Nav/Nav.js
  src/Pages/Nav/Nav.scss
  src/Routes.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#11 [19기 강서형]Feature/account new// update
  src/Pages/AccountPage/Login.js
  src/Pages/AccountPage/Login.scss
  src/Pages/AccountPage/SignUp.js
Labels: Status: 리뷰 요청

#4 [19기 김효진] Basket 추가기능 완료.
  .vscode/settings.json
  public/Basket/basket.json
  public/Basket/basketSubmit.json
  public/data/Category/category.json
  src/Components/SalePrice/SalePrice.js
  src/Pages/Basket/Basket.js
  src/Pages/Basket/Basket.scss
  src/Pages/Basket/MainBasket/Item.js
  src/Pages/Basket/MainBasket/MainBasket.js
  src/Pages/Basket/MainBasket/MainBasket.scss
  src/Pages/ProductListPage/ProductList.js
  src/Pages/ProductListPage/ProductListComponent/Products/Products.jsx
  src/Pages/ProductListPage/ProductListComponent/Products/ProductsItem/ProductsItem.jsx
  src/Pages/ProductListPage/ProductListComponent/Title/SubTitle.js
  src/Pages/ProductListPage/ProductListComponent/Title/Title.js
  src/Routes.js
  src/styles/reset.scss
  src/utils/function.js
Labels: Status: 리뷰 요청, Status: 수정 요청

#10 [19기 이종호] Feature/main event 완료
  public/data/MainData/Best.json
  public/data/MainData/Hashtag.json
  public/data/MainData/Review.json
  src/Pages/MainPage/Main.js
  src/Pages/MainPage/MainBody/Best.js
  src/Pages/MainPage/MainBody/Best.scss
  src/Pages/MainPage/MainBody/HotKeyword.js
  src/Pages/MainPage/MainBody/HotKeyword.scss
  src/Pages/MainPage/MainBody/RealReview.js
  src/Pages/MainPage/MainBody/RealReview.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#13 [19기 이종호] Feature/pay event
  public/data/Pay/PayData.json
  src/Functions/funcs.js
  src/Pages/FavoriteProduct/FavoriteProduct.js
  src/Pages/PayPage/Pay.js
  src/Pages/PayPage/PayBody.js
  src/Pages/PayPage/PayBody/PayDelivery.js
  src/Pages/PayPage/PayBody/PayDelivery.scss
  src/Pages/PayPage/PayBody/PayOrder.js
  src/Pages/PayPage/PayBody/PayOrder.scss
  src/Pages/PayPage/PayContainer.js
Labels: Status: 리뷰 요청

#17 [19기 이종호] Refactoring/code style
  public/index.html
  src/Pages/AccountPage/Login.js
  src/Pages/AccountPage/SignUp.js
  src/Pages/Basket/Basket.js
  src/Pages/MainPage/MainBody/Banner.js
  src/Pages/MainPage/MainBody/Banner.scss
  src/Pages/MainPage/MainBody/Best.js
  src/Pages/MainPage/MainBody/Best.scss
  src/Pages/MainPage/MainBody/HotKeyword.js
  src/Pages/MainPage/MainBody/HotKeyword.scss
  src/Pages/MainPage/MainBody/JustInfo.js
  src/Pages/MainPage/MainBody/JustInfo.scss
  src/Pages/MainPage/MainBody/RealReview.js
  src/Pages/MainPage/MainBody/RealReview.scss
  src/Pages/ProductInfoPage/ProductDetail.js
  src/Pages/ProductInfoPage/ProductInfoimage.js
  src/Pages/ProductInfoPage/ProductSub.js
  src/Routes.js
Labels: Status: 리뷰 요청
